name: Build and Release

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Restore dependencies
      run: dotnet restore ./WAIModelDownloader/WAIModelDownloader.sln

    - name: Publish project
      run: dotnet publish --configuration Release --output ./WAIModelDownloader/bin/Release/net6.0/publish ./WAIModelDownloader/WAIModelDownloader.sln

    - name: Create Releases directory
      run: New-Item -ItemType Directory -Force -Path ./Releases

    - name: Copy build artifacts with timestamp and commit hash
      run: |
        $timestamp = Get-Date -Format "yyyyMMddHHmmss"
        $commit = (git rev-parse --short HEAD)
        Copy-Item -Path ./WAIModelDownloader/bin/Release/net6.0/publish/WAIModelDownloader.exe -Destination ./Releases/WAIModelDownloader_$timestamp_$commit.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: WAIModelDownloader
        path: ./Releases/WAIModelDownloader_*.exe
        if-no-files-found: error
