name: Build and Release

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore ./WAIModelDownloader/WAIModelDownloader.sln

    - name: Publish project
      run: dotnet publish --configuration Release --output ./WAIModelDownloader/bin/Release/net6.0/publish ./WAIModelDownloader/WAIModelDownloader.sln

    - name: Create Releases directory
      run: New-Item -ItemType Directory -Force -Path ./Releases

    - name: Zip build artifacts with timestamp and commit hash
      run: |
        $timestamp = Get-Date -Format "yyyyMMddHHmmss"
        $commit = (git rev-parse --short HEAD)
        Compress-Archive -Path ./WAIModelDownloader/bin/Release/net6.0/publish/* -DestinationPath ./Releases/WAIModelDownloader_$timestamp_$commit.zip

    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push release zip
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git add ./Releases/WAIModelDownloader_*.zip
        git commit -m "Add release zip file"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
        git push origin HEAD:$(git rev-parse --abbrev-ref HEAD)

